plugins {
	id 'dev.architectury.loom-no-remap'
	id 'dev.architectury.loom'
}
sourceSets {
	main {
		resources.srcDir project.file('src/main/generated')
	}
}
loom { accessWidenerPath = project.file('src/main/resources/ice_skates.accesswidener') }
dependencies {
	minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
	compileOnly "net.fabricmc:fabric-loader:${rootProject.loader_version}"
}
